files:
  include: './src/scss/**/*.scss'
options:
  formatter: stylish
rules:
  class-name-format: &class-name-format
    - 2
    - convention: ^(([A-Z][a-z]*)+$|(([A-Z][a-z]*)+|u|is|js)(-|--)([a-z]+([a-z]|[A-Z])*)+|(([A-Z][a-z]*)+|u|is|js)(-|--)([a-z]+([a-z]|[A-Z])*)+(--[a-z]+([a-z]|[A-Z])*)+)|[ng]-(\w)+(-(\w)*)*$
  empty-line-between-blocks:
    - 2
    - ignore-single-line-rulesets: false
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  function-name-format: 2
  hex-length:
    - 2
    - style: long
  indentation:
    - 2
    - size: 2
  leading-zero:
    - 2
    - include: true
  mixin-name-format: 1
  nesting-depth:
    - 2
    - max-depth: 2
  no-ids: 2
  no-important: 2
  placeholder-name-format: *class-name-format
  quotes:
    - 2
    - style: single
  variable-name-format: *class-name-format
