files:
  include: './src/scss/**/*.scss'
options:
  formatter: stylish
rules:
  class-name-format:
    - 2
    - convention: hyphenatedbem
  empty-line-between-blocks:
    - 2
    - ignore-single-line-rulesets: false
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  function-name-format: 2
  hex-length:
    - 2
    - style: long
  indentation:
    - 2
    - size: 2
  leading-zero:
    - 2
    - include: true
  mixin-name-format: 1
  nesting-depth:
    - 2
    - max-depth: 2
  no-ids: 2
  no-important: 2
  placeholder-name-format:
    - 2
    - convention: hyphenatedbem
  quotes:
    - 2
    - style: single
  variable-name-format:
    - 2
    - convention: hyphenatedlowercase
